// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class ReleaseNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 1280
    let windowHeight: Int = 720

    // MARK: - Window Title
    let windowTitle: String = "Chess"

    // MARK: - Animation control
    let withAnimation: Bool = true

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_release.png"
    let imageWidth: Int = 512
    let imageHeight: Int = 512
}
